### ISSUE TITLE
Test suite

### ISSUE THREAD

**Issue by bglusman** [sschepens/toiler#8]
@sschepens hey so I was looking at maybe starting on the config extension for #7 and thought I'd start by reviewing existing tests, maybe try and even start TDD with a new failing test (I'm not great at TDD but like to try now and then), but I'm not seeing any tests in the repo...  any chance you just didn't commit them for some reason? If not, maybe I can adapt some of shoryuken's tests and get a suite running on Travis or something, seems like we'd like at least decent test coverage going forward to enable safe releases.

**Comment by bglusman** [comment]
@sschepens Ping?  We may just fork and do this ourselves either way but definitely appreciate your feedback and buy in!  Thanks!

**Comment by sschepens** [comment]
@bglusman sorry for the delay, been busy. When I started toiler we were in a rush with a project and needed a quick replacement to shoryuken, that's why I never got to write any tests, I'm dedicating some of my free time to write some.
If you feel like contributing too it would be great!
I don't think much of Shrouyken's tests can be ported, a lot has changed since, maybe `Cli` remains somehow similar.

**Comment by bglusman** [comment]
Since this is merged in now with at least some tests closing this, thanks @sschepens !
